name: CustomOreGen
version: ${project.version}
description: Controls the Ore-Generator
author: Linus122
depend: []
softdepend: [ASkyBlock, AcidIsland, uSkyBlock, SkyBlock, BentoBox, IslandWorld]
main: spaceio.customoregen.CustomOreGen
api-version: 1.13
commands:
   customoregen:
     description: reloads the plugin
     usage: /CustomOreGen